title: Worbcoin - P2P & Supermarket
logo: "assets/logo.png"
favicon: "assets/logo.png"
description: Trade crypto on Worbcoin P2P + Shop groceries with $WRB at Worb Supermarket
url: "https://worbcoin.org"
baseurl: ""
remote_theme: pmarsceill/just-the-docs
search_enabled: true
heading_anchors: true
nav_list:
    - title: Home
    url: /
    - title: P2P
    group: P2P
    - title: Trade
    url: /trade
    - title: Markets
    url: /markets
    - title: Wallet
    url: /wallet
    - title: Supermarket
    group: Supermarket
    - title: Worb Supermarket
    url: /supermarket
    - title: Discount Shop
    url: /discount
    - title: WRB Chain
    url: /space
    - title: About
    url: /about
footer_content: "© 2026 Worbcoin. Trade P2P + Shop groceries with $WRB. Trade responsibly."
