nav_list:
    - title: Home
    url: /
    - title: P2P
    group: P2P
    - title: Trade
    url: /trade
    - title: Markets
    url: /markets
    - title: Wallet
    url: /wallet
    - title: Supermarket
    group: Supermarket
    - title: Worb Supermarket
    url: /supermarket
    - title: Discount Shop
    url: /discount
    - title: WRB Chain
    url: /space
    - title: About
    url: /about
